#!/usr/bin/env node
/*
 * Generate the derived half of a blueprint.
 *
 * A blueprint has two halves and only one of them is a judgement. The written
 * half says where the seams fall for a shape and which position owns what — it
 * came out of a decomposed reference and a generator could not derive it. The
 * other half is a collation: every capability this archetype owes, what each
 * one requires, which decisions it leaves to a builder, and what it discharges
 * in the assurance catalog.
 *
 * That half was being maintained by hand, which meant it was a copy of the
 * capabilities that could disagree with them — and would, on the first
 * capability added after somebody stopped looking at it. So it is generated
 * from the same files the linter checks, into a separate document the written
 * half links to, and the check below fails when the generated file on disk is
 * not what these capabilities produce.
 *
 *   node tools/blueprint.js A6          # write it
 *   node tools/blueprint.js A6 --check  # fail if it is stale (CI)
 */
const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const ROOT = path.join(__dirname, "..");
const load = (p) => yaml.load(fs.readFileSync(path.join(ROOT, p), "utf8"));

const archetype = process.argv[2] || "A6";
const checking = process.argv.includes("--check");

const arch = load("taxonomy/archetypes.yaml");
const layers = load("taxonomy/layers.yaml");
const named = arch.archetypes.find((a) => a.id === archetype);
if (!named) {
  console.error(`no archetype ${archetype}`);
  process.exit(2);
}

const LAYER = new Map(layers.layers.map((l) => [l.id, l.name]));

const owed = fs
  .readdirSync(path.join(ROOT, "capabilities"))
  .filter((f) => f.endsWith(".yaml"))
  .map((f) => yaml.load(fs.readFileSync(path.join(ROOT, "capabilities", f), "utf8")))
  .filter((c) => c.archetypes.includes(archetype) && c.status === "active")
  .sort((a, b) => a.id.localeCompare(b.id));

/*
 * Grouped by layer rather than by identifier. A builder reads this while
 * building one part of the thing, and the question they have is "what does the
 * context assembler owe" — not "what is AHC-0038". The identifier order is the
 * order they were written in, which is chronology and not architecture.
 */
const byLayer = new Map();
for (const cap of owed) {
  for (const layer of cap.layers) {
    if (!byLayer.has(layer)) byLayer.set(layer, []);
    byLayer.get(layer).push(cap);
  }
}
const ordered = [...byLayer.keys()].sort(
  (a, b) => Number(a.slice(1)) - Number(b.slice(1))
);

const lines = [
  `# ${archetype} · ${named.name} — what it owes`,
  "",
  "*Generated by `tools/blueprint.js`. Never edit by hand — regenerate.*",
  "",
  "The derived half of this blueprint: every capability this shape owes,",
  "collated from the capabilities themselves rather than restated beside them.",
  `The written half — where the seams fall, which position owns what — is in`,
  `[${archetype}-${named.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md](${archetype}-${named.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md).`,
  "",
  `**${owed.length} capabilities**, across ${ordered.length} of ${LAYER.size} layers.`,
  "",
  "| Layer | Owes |",
  "|---|---|",
];
for (const layer of ordered) {
  const ids = byLayer.get(layer).map((c) => c.id).join(", ");
  lines.push(`| **${layer}** ${LAYER.get(layer)} | ${ids} |`);
}

for (const layer of ordered) {
  lines.push("", `## ${layer} · ${LAYER.get(layer)}`, "");
  for (const cap of byLayer.get(layer)) {
    lines.push(`### ${cap.id} — ${cap.title.trim()}`, "");
    lines.push(`*${cap.level}${cap.core ? " · core" : ""} · ${cap.concern}*`, "");
    lines.push(cap.requirement.trim(), "");
    const keyed = (cap.design_decisions || []).filter((d) => d.key);
    if (keyed.length) {
      lines.push("**Answer in the profile:**", "");
      for (const d of keyed) lines.push(`- \`${cap.id}/${d.key}\` — ${d.question}`);
      lines.push("");
    }
    if (cap.discharges && cap.discharges.length) {
      lines.push(`**Discharges** ${cap.discharges.join(", ")}`, "");
    }
  }
}

const out = lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
const dest = path.join(ROOT, "blueprints", `${archetype}-owes.generated.md`);

if (checking) {
  const current = fs.existsSync(dest) ? fs.readFileSync(dest, "utf8") : "";
  if (current !== out) {
    console.error(
      `blueprints/${archetype}-owes.generated.md is stale — run: node tools/blueprint.js ${archetype}`
    );
    process.exit(1);
  }
  console.log(`blueprint ${archetype}: up to date (${owed.length} capabilities)`);
} else {
  fs.writeFileSync(dest, out);
  console.log(`blueprints/${archetype}-owes.generated.md  ${owed.length} capabilities`);
}
